# Generated by Django 5.0 on 2023-12-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_text",
                    models.CharField(max_length=150, verbose_name="About Sale"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("img", models.ImageField(upload_to="media", verbose_name="Image")),
            ],
            options={
                "verbose_name": "General Slider",
                "verbose_name_plural": "General Sliders",
            },
        ),
    ]
