# Generated by Django 5.0 on 2023-12-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderTop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FAQs", models.TextField(verbose_name="FAQs")),
                ("Help", models.TextField(verbose_name="Help")),
                ("Support", models.TextField(verbose_name="Support")),
                ("facebook", models.URLField(verbose_name="Facebook URL")),
                ("twitter", models.URLField(verbose_name="Twitter URL")),
                ("linkedin", models.URLField(verbose_name="LinkedIn URL")),
                ("instagram", models.URLField(verbose_name="Instagram URL")),
                ("youtube", models.URLField(verbose_name="Youtube URL")),
            ],
            options={
                "verbose_name": "Header Top",
                "verbose_name_plural": "Header Top",
            },
        ),
    ]
