# Generated by Django 5.0 on 2023-12-23 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_category_subcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Product Sub Category",
                "verbose_name_plural": "Product Sub Categories",
            },
        ),
    ]
