# Generated by Django 5.0 on 2023-12-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_category_options_alter_subcategory_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Color Name")),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to="media", verbose_name="Product Image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5, verbose_name="Color Name")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "price",
                    models.PositiveSmallIntegerField(verbose_name="Product Price"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Discount Size"
                    ),
                ),
                ("about", models.TextField(verbose_name="About Product")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook URL")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter URL")),
                ("linedin", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                (
                    "pinterest",
                    models.URLField(blank=True, verbose_name="Pinterest URL"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("information", models.TextField(verbose_name="Information")),
                ("colors", models.ManyToManyField(to="main.color")),
                ("images", models.ManyToManyField(to="main.image")),
                ("sizes", models.ManyToManyField(to="main.size")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very good"),
                            (5, "5 - Excellent"),
                        ],
                        max_length=1,
                    ),
                ),
                ("review", models.TextField(verbose_name="Review Text")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_rev",
                        to="main.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rev_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
