# Generated by Django 5.0 on 2023-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_product_is_trandy"),
    ]

    operations = [
        migrations.CreateModel(
            name="StayUpdated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Customer Email"),
                ),
            ],
            options={
                "verbose_name": "Stay Updated",
                "verbose_name_plural": "Stay Updated",
            },
        ),
    ]
