# Generated by Django 5.0 on 2023-12-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_stayupdated"),
    ]

    operations = [
        migrations.CreateModel(
            name="CooperativeCompanies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
            ],
        ),
    ]
