# Generated by Django 5.0 on 2023-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_cooperativecompanies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Customer Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Customer Email"),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=50, verbose_name="Customer Message Subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message text")),
            ],
            options={
                "verbose_name": "ContactUs",
                "verbose_name_plural": "ContactUs",
            },
        ),
    ]
