# Generated by Django 5.0 on 2023-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=5, verbose_name="Size Name"),
        ),
    ]
