# Generated by Django 5.0 on 2023-12-28 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_size_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_trandy",
            new_name="is_trendy",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="linedin",
            new_name="linkedin",
        ),
    ]
