# Generated by Django 5.0 on 2024-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
